version: "3.9"  # optional since v1.27.0

services:
  udagram-frontend:
    ports:
      - "8100:8100"

  udagram-api-feed:
    ports:
      - "7900:7900"

  udagram-api-user:
    ports:
      - "8000:8000"

  udagram-reverseproxy:
    ports:
      - "8200:8200"